Fix interactables, update scene hierarchy to be more clear for end-user
charisma-ai/unity-plug-n-play pull request #1
Opened 2024-05-01 14:07 UTC by RobCharisma

- Fixed interactable meta functions
    - Metadata sent from graph functions included multiple interactables at once, while the interactable functions only handled 1 object at a time, so they didn't work. Now they handle all the objects.
- Scene hierarchy updated
    - Renamed NPCs and added their IDs to match the plug n play NPCs
    - Renamed some scene objects to be more clear and eye-catching for the end-user
    - Removed MainThreadConsumer, this is to be merged alongside this [SDK PR](https://github.com/charisma-ai/charisma-sdk-unity/pull/27)

2024-05-01 16:14 UTC, RaduDumitriu-Dev requested changes
Looks good! Only thing would be clearing the scene of the playthrough parameters and I can approve

2024-05-01 16:14 UTC, RaduDumitriu-Dev commented on Samples~/Scripts/Playthrough/Metadata/AllowInteractableFunction.cs
> +            string[] subjectTargets = metadataValue.Split(',');
awesome, think we have this in some of our other PnP projects but I've forgot to port it over. Great call.

2024-05-01 16:14 UTC, RaduDumitriu-Dev commented on Samples~/Scenes/PlugNPlaySample.unity
small thing, but playthrough instance still has the Playthrough parameters in the sample scene. We don't normally include these in our packages partly out of safety and to encourage people to sign up on the platform.

2024-05-01 16:14 UTC, RaduDumitriu-Dev commented on Samples~/Scenes/PlugNPlaySample.unity
Hierarchy organisation looks good, a lot nicer to sift thru.

2024-05-01 16:20 UTC, RobCharisma commented on Samples~/Scenes/PlugNPlaySample.unity
Should be fixed now!

2024-05-02 10:27 UTC, RaduDumitriu-Dev commented
Ran another test on this - will need to update the Charisma.Audio namespace references in the PlaythroughInstances from /~samples/. That should be the only other change needed

2024-05-02 10:49 UTC, RaduDumitriu-Dev approved these changes

2024-05-02 13:14 UTC, merged